/** Shared help copy for InfoTooltip (dashboard / analysis). */

export const TOOLTIP_CDM_UPLOAD_HISTORY =
  "Displays previously uploaded CDM files, including processing status, validation results, and upload details.";

export const TOOLTIP_RISK_TREND_CHART =
  "Visualizes how high-risk and low-risk assessment results change over time based on recent user analyses.";

export const TOOLTIP_RISK_DISTRIBUTION_CHART =
  "Displays the overall proportion of High and Low risk assessments generated by the system.";

export const TOOLTIP_CDM_EVENTS_TABLE =
  "Displays grouped CDM events with their latest conjunction information, event size, and collision probability for monitoring and event management.";

export const TOOLTIP_RISK_ASSESSMENTS_TABLE =
  "Tracks completed collision risk analyses, including assessment type, classification result, confidence score, and recommended maneuver decision.";
